// Code generated by MockGen. DO NOT EDIT.
// Source: shop.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/darialissi/avito_merch_service/internal/models"
	dto "github.com/darialissi/avito_merch_service/internal/schemas/dto"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockShopRepository is a mock of ShopRepository interface.
type MockShopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopRepositoryMockRecorder
}

// MockShopRepositoryMockRecorder is the mock recorder for MockShopRepository.
type MockShopRepositoryMockRecorder struct {
	mock *MockShopRepository
}

// NewMockShopRepository creates a new mock instance.
func NewMockShopRepository(ctrl *gomock.Controller) *MockShopRepository {
	mock := &MockShopRepository{ctrl: ctrl}
	mock.recorder = &MockShopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopRepository) EXPECT() *MockShopRepositoryMockRecorder {
	return m.recorder
}

// GetItemByName mocks base method.
func (m *MockShopRepository) GetItemByName(ctx context.Context, name string) (*models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByName", ctx, name)
	ret0, _ := ret[0].(*models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByName indicates an expected call of GetItemByName.
func (mr *MockShopRepositoryMockRecorder) GetItemByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByName", reflect.TypeOf((*MockShopRepository)(nil).GetItemByName), ctx, name)
}

// GetTransactionsByUserID mocks base method.
func (m *MockShopRepository) GetTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByUserID indicates an expected call of GetTransactionsByUserID.
func (mr *MockShopRepositoryMockRecorder) GetTransactionsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByUserID", reflect.TypeOf((*MockShopRepository)(nil).GetTransactionsByUserID), ctx, userID)
}

// GetUserItem mocks base method.
func (m *MockShopRepository) GetUserItem(ctx context.Context, userID, itemID uuid.UUID, forUpdate bool) (*models.UserItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserItem", ctx, userID, itemID, forUpdate)
	ret0, _ := ret[0].(*models.UserItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserItem indicates an expected call of GetUserItem.
func (mr *MockShopRepositoryMockRecorder) GetUserItem(ctx, userID, itemID, forUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserItem", reflect.TypeOf((*MockShopRepository)(nil).GetUserItem), ctx, userID, itemID, forUpdate)
}

// GetUserItemsByUserID mocks base method.
func (m *MockShopRepository) GetUserItemsByUserID(ctx context.Context, userID uuid.UUID) ([]models.UserItemExtended, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserItemsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.UserItemExtended)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserItemsByUserID indicates an expected call of GetUserItemsByUserID.
func (mr *MockShopRepositoryMockRecorder) GetUserItemsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserItemsByUserID", reflect.TypeOf((*MockShopRepository)(nil).GetUserItemsByUserID), ctx, userID)
}

// GetUsersCoinsByUsernames mocks base method.
func (m *MockShopRepository) GetUsersCoinsByUsernames(ctx context.Context, usernames []string, forUpdate bool) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersCoinsByUsernames", ctx, usernames, forUpdate)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersCoinsByUsernames indicates an expected call of GetUsersCoinsByUsernames.
func (mr *MockShopRepositoryMockRecorder) GetUsersCoinsByUsernames(ctx, usernames, forUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersCoinsByUsernames", reflect.TypeOf((*MockShopRepository)(nil).GetUsersCoinsByUsernames), ctx, usernames, forUpdate)
}

// SaveTransaction mocks base method.
func (m *MockShopRepository) SaveTransaction(ctx context.Context, fromUserID, toUserID uuid.UUID, amount float64) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTransaction", ctx, fromUserID, toUserID, amount)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTransaction indicates an expected call of SaveTransaction.
func (mr *MockShopRepositoryMockRecorder) SaveTransaction(ctx, fromUserID, toUserID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTransaction", reflect.TypeOf((*MockShopRepository)(nil).SaveTransaction), ctx, fromUserID, toUserID, amount)
}

// SaveUserItem mocks base method.
func (m *MockShopRepository) SaveUserItem(ctx context.Context, userID, itemID uuid.UUID, quantity int) (*models.UserItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserItem", ctx, userID, itemID, quantity)
	ret0, _ := ret[0].(*models.UserItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUserItem indicates an expected call of SaveUserItem.
func (mr *MockShopRepositoryMockRecorder) SaveUserItem(ctx, userID, itemID, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserItem", reflect.TypeOf((*MockShopRepository)(nil).SaveUserItem), ctx, userID, itemID, quantity)
}

// UpdateUserCoinsByUsername mocks base method.
func (m *MockShopRepository) UpdateUserCoinsByUsername(ctx context.Context, username string, coins float64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserCoinsByUsername", ctx, username, coins)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserCoinsByUsername indicates an expected call of UpdateUserCoinsByUsername.
func (mr *MockShopRepositoryMockRecorder) UpdateUserCoinsByUsername(ctx, username, coins interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserCoinsByUsername", reflect.TypeOf((*MockShopRepository)(nil).UpdateUserCoinsByUsername), ctx, username, coins)
}

// UpdateUserItemQuantity mocks base method.
func (m *MockShopRepository) UpdateUserItemQuantity(ctx context.Context, userID, itemID uuid.UUID, quantity int) (*models.UserItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserItemQuantity", ctx, userID, itemID, quantity)
	ret0, _ := ret[0].(*models.UserItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserItemQuantity indicates an expected call of UpdateUserItemQuantity.
func (mr *MockShopRepositoryMockRecorder) UpdateUserItemQuantity(ctx, userID, itemID, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserItemQuantity", reflect.TypeOf((*MockShopRepository)(nil).UpdateUserItemQuantity), ctx, userID, itemID, quantity)
}

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// RunReadCommitted mocks base method.
func (m *MockTransactionManager) RunReadCommitted(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunReadCommitted", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadCommitted indicates an expected call of RunReadCommitted.
func (mr *MockTransactionManagerMockRecorder) RunReadCommitted(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadCommitted", reflect.TypeOf((*MockTransactionManager)(nil).RunReadCommitted), ctx, f)
}

// RunRepeatableRead mocks base method.
func (m *MockTransactionManager) RunRepeatableRead(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRepeatableRead", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRepeatableRead indicates an expected call of RunRepeatableRead.
func (mr *MockTransactionManagerMockRecorder) RunRepeatableRead(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRepeatableRead", reflect.TypeOf((*MockTransactionManager)(nil).RunRepeatableRead), ctx, f)
}

// RunSerializable mocks base method.
func (m *MockTransactionManager) RunSerializable(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSerializable", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunSerializable indicates an expected call of RunSerializable.
func (mr *MockTransactionManagerMockRecorder) RunSerializable(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSerializable", reflect.TypeOf((*MockTransactionManager)(nil).RunSerializable), ctx, f)
}

// MockShopUsecases is a mock of ShopUsecases interface.
type MockShopUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockShopUsecasesMockRecorder
}

// MockShopUsecasesMockRecorder is the mock recorder for MockShopUsecases.
type MockShopUsecasesMockRecorder struct {
	mock *MockShopUsecases
}

// NewMockShopUsecases creates a new mock instance.
func NewMockShopUsecases(ctrl *gomock.Controller) *MockShopUsecases {
	mock := &MockShopUsecases{ctrl: ctrl}
	mock.recorder = &MockShopUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopUsecases) EXPECT() *MockShopUsecasesMockRecorder {
	return m.recorder
}

// BuyItem mocks base method.
func (m *MockShopUsecases) BuyItem(ctx context.Context, username string, data *dto.BuyItemData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyItem", ctx, username, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuyItem indicates an expected call of BuyItem.
func (mr *MockShopUsecasesMockRecorder) BuyItem(ctx, username, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyItem", reflect.TypeOf((*MockShopUsecases)(nil).BuyItem), ctx, username, data)
}

// Info mocks base method.
func (m *MockShopUsecases) Info(ctx context.Context, username string) (*dto.AggregatedInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx, username)
	ret0, _ := ret[0].(*dto.AggregatedInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockShopUsecasesMockRecorder) Info(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockShopUsecases)(nil).Info), ctx, username)
}

// SendCoin mocks base method.
func (m *MockShopUsecases) SendCoin(ctx context.Context, username string, data *dto.TransactionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCoin", ctx, username, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCoin indicates an expected call of SendCoin.
func (mr *MockShopUsecasesMockRecorder) SendCoin(ctx, username, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCoin", reflect.TypeOf((*MockShopUsecases)(nil).SendCoin), ctx, username, data)
}
