services:

  app:
    container_name: app_container
    build:
      context: .
    environment:
      CONFIG_PATH: "/app/configs/.config.prod.yml"
    depends_on:
      db_prod:
        condition: service_healthy
      migrate_up_prod:
        condition: service_completed_successfully
      redis_prod:
        condition: service_healthy
    profiles: ["prod"]

  db_prod:
    image: postgres:18
    container_name: db_prod_container
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5435
    env_file:
      - .env
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["prod"]

  migrate_up_prod:
    image: goose-migration
    container_name: migrate_up_prod_container
    env_file:
      - .env
    depends_on:
      - db_prod
    command: ["up"]
    restart: "no"
    profiles: ["prod"]

  redis_prod:
    image: redis:8.4-alpine
    container_name: redis_prod
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["prod"]

  db_dev:
    image: postgres:18
    container_name: db_dev_container
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5436
    env_file:
      - .env
    ports:
      - '5436:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql
    profiles: ["dev"]

  migrate_up_dev:
    image: goose-migration
    container_name: migrate_up_dev_container
    env_file:
      - .env
    depends_on:
      - db_dev
    command: ["up"]
    restart: "no"
    profiles: ["dev"]

  redis_dev:
    image: redis:8.4-alpine
    container_name: redis_dev
    ports:
      - "6380:6379"
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["dev"]

  db_test:
    image: postgres:18
    container_name: db_test_container
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5437
    env_file:
      - .env
    ports:
      - '5437:5432'
    profiles: ["test"]

  migrate_up_test:
    image: goose-migration
    container_name: migrate_up_test_container
    env_file:
      - .env
    depends_on:
      - db_test
    command: ["up"]
    restart: "no"
    profiles: ["test"]

  redis_test:
    image: redis:8.4-alpine
    container_name: redis_test
    ports:
      - "6381:6379"
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["test"]


volumes:
  postgres_data:
  redis_data:
  redis_dev_data:
  postgres_dev_data: