app:
  port: :8080
  timeout:
    request: 10s
    graceful: 30s

  jwt:
    access:
      exp: 30m
      secret: ryurtuyggjguhuiyih
    refresh:
      exp: 24h
      secret: kljslkjdkjskjksjl

db:
  host: localhost
  port: 5436
  name: postgres
  user: postgres
  password: qwerty

  pool:
    max_conns: 10
    min_conns: 5
    max_conn_lifetime: 1h30m
    max_conn_idletime: 10m

redis:
  host: localhost
  port: 6380
  password: qwerty