openapi: 3.0.0
info:
  title: API Avito shop
  version: 1.0.0

servers:
  - url: http://localhost:8080

security:
  - BearerAuth: []

tags:
  - name: auth
    description: Регистрация / Aутентификация
  - name: shop
    description: Покупки / Tранзакции

paths:
  /api/info:
    get:
      tags:
        - shop
      summary: Получение информации о монетах, инвентаре и истории транзакций.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Успешный ответ.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
        '400':
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/sendCoin:
    post:
      tags:
        - shop
      summary: Отправление монет другому пользователю.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCoinRequest'
      responses:
        '200':
          description: Успешный ответ.
        '400':
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/buy/{item}:
    post:
      tags:
        - shop
      summary: Покупка предмета за монеты.
      security:
        - BearerAuth: []
      parameters:
        - name: item
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyItemRequest'
      responses:
        '200':
          description: Успешный ответ.
        '400':
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/register:
    post:
      tags:
        - auth
      summary: Регистрация нового пользователя.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Успешная регистрация.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth:
    post:
      tags:
        - auth
      summary: Аутентификация и получение JWT-токенов.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Успешная аутентификация.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    InfoResponse:
      type: object
      properties:
        coins:
          type: integer
          description: Количество доступных монет.
        inventory:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: Тип предмета.
              quantity:
                type: integer
                description: Количество предметов.
        coinHistory:
          type: object
          properties:
            received:
              type: array
              items:
                type: object
                properties:
                  fromUser:
                    type: string
                    description: Имя пользователя, который отправил монеты.
                  amount:
                    type: integer
                    description: Количество полученных монет.
            sent:
              type: array
              items:
                type: object
                properties:
                  toUser:
                    type: string
                    description: Имя пользователя, которому отправлены монеты.
                  amount:
                    type: integer
                    description: Количество отправленных монет.

    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          description: Сообщение об ошибке, описывающее проблему.

    AuthRequest:
      type: object
      properties:
        username:
          type: string
          description: Имя пользователя для аутентификации.
        password:
          type: string
          format: password
          description: Пароль для аутентификации.
      required:
        - username
        - password

    AuthResponse:
      type: object
      properties:
        access_token:
          type: string
          description: JWT-токен для доступа к защищенным ресурсам.
        refresh_token:
          type: string
          description: JWT-токен для обновления токенов.

    UserResponse:
      type: object
      properties:
        id:
          type: string
          description: ID пользователя.
        username:
          type: string
          description: Имя пользователя.
        coins:
          type: integer
          description: Количество монет у пользователя.
        createdAt:
          type: string
          format: date-time
          description: Дата и время создания пользователя.

    SendCoinRequest:
      type: object
      properties:
        toUser:
          type: string
          description: Имя пользователя, которому нужно отправить монеты.
        amount:
          type: integer
          description: Количество монет, которые необходимо отправить.
      required:
        - toUser
        - amount

    BuyItemRequest:
      type: object
      properties:
        quantity:
          type: integer
          description: Количество предметов для покупки.
      required:
        - quantity